### ISSUE TITLE
More examples please.

### ISSUE THREAD

**Issue by soloviofff** [mtvkand/invest-nodejs-grpc-sdk#5]
Можешь пожалуйста в [этом примере](https://github.com/mtvkand/invest-nodejs-grpc-sdk/blob/master/src/examples/marketDataStream.ts) показать как вызывать все генераторы в одном marketDataStream?

Т.к. на первом грейде [доступно всего 2](https://tinkoff.github.io/investAPI/limits/) marketDataStream, хорошо бы эффективно их использовать.

**Comment by mtvkand** [comment]
Hey @soloviofff  , see if the examples below has what you need. First link should help you to get candles by figi, second can get array of figi as a parameter of method and create subscription for this instruments.

https://github.com/mtvkand/invest-nodejs-grpc-sdk/blob/8532869563b341ad585673776c4d98ac6abdf952/src/examples/marketData.ts#L8 and 
https://github.com/mtvkand/invest-nodejs-grpc-sdk/blob/8532869563b341ad585673776c4d98ac6abdf952/src/examples/marketDataStream.ts#L68

If not, feel free to open PR with new example.

**Comment by suenot** [comment]
https://github.com/mtvkand/invest-nodejs-grpc-sdk/blob/8532869563b341ad585673776c4d98ac6abdf952/src/examples/marketDataStream.ts#L80
But you run only one generator in example only for LastPrices. `createSubscriptionTradesRequest`, `createSubscriptionOrderBookRequest`, `createSubscriptionCandleRequest` не вызываются.

**Comment by mtvkand** [comment]
> https://github.com/mtvkand/invest-nodejs-grpc-sdk/blob/8532869563b341ad585673776c4d98ac6abdf952/src/examples/marketDataStream.ts#L80
> 
> 
> But you run only one generator in example only for LastPrices.

Можно например еще один генератор добавить, через таймаут, самое примитивное решение в данном случае

!(async function example() {
  const { marketDataStream } = createSdk(process.env.TOKEN || '');

  try {
    let keepCalling = true;

    setTimeout(function () {
      keepCalling = false;
    }, 5000);

    const timer = (time: number) => new Promise(resolve => setTimeout(resolve, time));

    //генератор для последней цены инструмента и свечей
    async function* createRequest(): AsyncIterable<DeepPartial<MarketDataRequest>> {
      while (keepCalling) {
        await timer(1000);
        yield MarketDataRequest.fromPartial({
          subscribeLastPriceRequest: {
            subscriptionAction: SubscriptionAction.SUBSCRIPTION_ACTION_SUBSCRIBE,
            instruments: [{ figi: 'BBG000N9MNX3' }],
          },
        });
        await timer(1000);
        yield MarketDataRequest.fromPartial({
          subscribeCandlesRequest: {
            subscriptionAction: SubscriptionAction.SUBSCRIPTION_ACTION_SUBSCRIBE,
            instruments: [{ figi: 'BBG000N9MNX3', interval: SubscriptionInterval.SUBSCRIPTION_INTERVAL_ONE_MINUTE }],
          },
        });
      }
    }

    const response = marketDataStream.marketDataStream(createRequest());

    for await (const num of response) {
      console.log(num);
    }
  } catch (e) {
    console.log(e);
  }
})();

**Comment by suenot** [comment]
Спасибо за помощь! Стоит добавить в примеры, т.к. многим пригодится.

**Comment by mtvkand** [comment]
> Спасибо за помощь! Стоит добавить в примеры, т.к. многим пригодится.

Буду рад, если откроете пуллреквест с таким примером. Если будут еще вопросы - обращайтесь. Закрываю ишью.
